In [5]:
# Consider the below code to answer further questions:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [3]:
# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

# Yes, there is a difference in the data types of list_ and array_list. list_ is a Python list, which is a generic container that can hold any type of object.
# On the other hand, array_list is a NumPy array, which has a fixed type for all its elements and will store data in a more efficient, contiguous manner.

import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object = list_)
print(f"Data type of list_: {type(list_)}")
print(f"Data type of array_list: {type(array_list)}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          

Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [6]:
# Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object = list_)
print("Data types of elements in list_:")

for item in list_:
    print(f"Type of '{item}': {type(item)}")
print("\nData types of elements in array_list:")

for item in array_list:
    print(f"Type of '{item}': {type(item)}")


Data types of elements in list_:
Type of '1': <class 'str'>
Type of '2': <class 'str'>
Type of '3': <class 'str'>
Type of '4': <class 'str'>
Type of '5': <class 'str'>

Data types of elements in array_list:
Type of '1': <class 'numpy.str_'>
Type of '2': <class 'numpy.str_'>
Type of '3': <class 'numpy.str_'>
Type of '4': <class 'numpy.str_'>
Type of '5': <class 'numpy.str_'>


In [ ]:
# Q3. Considering the following changes in the variable, array_list: array_list = np.array(object = list_, dtype = int)
# Will there be any difference in the data type of the elements present in both the variables, list_ and
# arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

Yes, there will be a difference. By setting dtype=int in the np.array() call, we are explicitly telling NumPy to convert the elements of the array into integers. 
This will affect the data type of the elements in array_list, while the elements in list_ remain strings.

In [ ]:
# Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [7]:
# Q4. Write a code to find the following characteristics of variable, num_array: (i) shape (ii) size

import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)
shape = num_array.shape
size = num_array.size

print(f"Shape of num_array: {shape}")
print(f"Size of num_array: {size}")


Shape of num_array: (2, 3)
Size of num_array: 6


In [8]:
# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
# [Hint: The size of the array will be 9 and the shape will be (3,3).]

import numpy as np
zero_matrix = np.zeros((3, 3))
print(f"3x3 Matrix of zeros:\n{zero_matrix}")


3x3 Matrix of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
# Q6. Create an identity matrix of shape (5,5) using numpy functions? [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

import numpy as np
identity_matrix = np.eye(5)
print(f"5x5 Identity Matrix:\n{identity_matrix}")


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
